### ISSUE TITLE
Access to python scripts aside from Jupiter notebook files

### ISSUE THREAD

**Issue by JonahRileyHuggins** [birtwistlelab/SPARCED#26]
Python scripts are inaccessible within the model repository jupyter_notebooks directory. The addition of such scripts that match the jupyter notebooks files is needed for running the model via command line.

**Comment by ChocolateCharlie** [comment]
Hey!
Why not run on the command line the code from the "bin" directory ? Isn't it supposed to do the same thing, though maybe not written exactly the same way ?
Just in case, you might want to avoid maintainance issues caused by duplicated code. I think that it is possible to create regular Python files and then to execute them in a Jupyter notebook by importing them, which could solve the "duplicated code" problem I just mentionned.
